---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "mqc_screenshots"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::mqc=1.10"
