# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: denoising_mppca
description: denoise a dataset with the Marchenko-Pastur principal component analysis
keywords:
  - nifti
  - denoising
  - mppca
tools:
  - MRtrix3:
      description: |
        MRtrix3 is a software package for various types of diffusion imaging
        data, including diffusion-weighted, diffusion-tensor, and q-ball imaging.
      homepage: https://www.mrtrix.org/
      identifier: 10.1016/j.neuroimage.2019.116137
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
        mandatory: true

    - dwi:
        type: file
        description: Nifti dwi file to denoise
        pattern: "*.{nii,nii.gz}"
        mandatory: true

    - mask:
        type: file
        description: Nifti mask file for the dwi
        pattern: "*.{nii,nii.gz}"
        mandatory: false

args:
  - extent:
      type: int
      description: |
        Set the patch size of the denoising filter.
        By default, the command will select the smallest
        isotropic patch size that exceeds the number of DW
        images in the input data

output:
  - image:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`

      - "*_dwi_denoised.nii.gz":
          type: file
          description: Denoised Nifti image file
          pattern: "*_dwi_denoised.{nii,nii.gz}"

  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml

authors:
  - "@scilus"
