# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: registration_tractogram
description: Apply a transform to a tractogram or multiple tractograms
keywords:
  - Diffusion MRI
  - Registration
  - Bundles
  - Tractogram
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - anat:
        type: file
        description: FA nifti format as anatomical image
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - affine:
        type: file
        description: ANTs affine transform
        pattern: "*.mat"
        ontologies: []
    - tractogram:
        type: file
        description: Tractogram or list of tractograms to register
        pattern: "*.{trk,tck}"
        ontologies: []
    - ref:
        type: file
        description: Reference anatomy for tck/vtk/fib/dpy file support (.nii or .nii.gz)
          (optional)
        pattern: "*.{tck,vtk,fib,dpy}"
        ontologies: []
    - deformation:
        type: file
        description: Path to the file containing a deformation field (optional)
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
output:
  warped_tractogram:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__*.{trk,tck}":
          type: file
          description: Warped tractogram(s).
          pattern: "*__*.{trk,tck}"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@scilus"
