---
name: "utils_templateflow"
description: |
  Module to fetch a population average template from TemplateFlow.
keywords:
  - template
  - population average
  - reference
tools:
  - "TemplateFlow":
      description: |
        TemplateFlow is a modular, version-controlled resource that
        allows researchers to use templates "off-the-shelf".
      homepage: "https://www.templateflow.org/"
      doi: "10.1038/s41592-022-01681-2"

input:
  - template:
      type: file
      description: |
        TemplateFlow template name.
        e.g. `MNI152NLin2009cAsym`
        Refer to the TemplateFlow documentation for available templates.
        https://www.templateflow.org/browse/

output:
  - folder:
      type: directory
      description: |
        Directory containing the requested template, with all available
        resolutions and masks/maps.
  - metadata:
      type: file
      description: |
        Metadata file containing information about the template.
      pattern: "*.json"
  - citations:
      type: file
      description: |
        File containing citations for the template.
      pattern: "*.bib"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@gagnonanthony"
maintainers:
  - "@gagnonanthony"
