---
name: "reconst_shsignal"
description: Compute the SH coefficient directly on the raw DWI signal
keywords:
  - sh
  - dwi
  - signal
tools:
  - "Scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - dwi:
      type: file
      description: Nifti DWI volume used to extract DTI metrics.
      pattern: "*.{nii,nii.gz}"

  - bval:
      type: file
      description: B-values in FSL format.
      pattern: "*.bval"

  - bvec:
      type: file
      description: B-vectors in FSL format.
      pattern: "*.bvec"

  - mask:
      type: file
      description: Nifti volume file used to mask the input image.
      pattern: "*.{nii,nii.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - sh_signal:
      type: file
      description: Output filename for the SH coefficients.
      pattern: "*__dwi_sh.{nii,nii.gz}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@AlexVCaron"
maintainers:
  - "@AlexVCaron"
