name: "reconst_shsignal"
description: Compute the SH coefficient directly on the raw DWI signal
keywords:
  - sh
  - dwi
  - signal
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti DWI volume used to extract DTI metrics.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"
        ontologies: []
    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"
        ontologies: []
    - mask:
        type: file
        description: Nifti volume file used to mask the input image.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - ue:
        type: integer
        description: "Dummy entry for lint to run succesfully. Refer to nf-core/tools#3483"
        pattern: "remove-me"
args:
  - dwi_shell_tolerance:
      type: integer
      description: Volumes with b-values that differ by this tolerance are considered
        of same weighting.
      default: 20
  - b0_thr_extract_b0:
      type: integer
      description: Volumes with b-values up to this threshold are considered b0 (unweighted).
      default: 10
  - shell_to_fit:
      type: integer
      description: Only use volumes with this b-value. Required if input is multi-shell.
      default: null
  - sh_order:
      type: integer
      description: Truncate spherical harmonics coefficients to this order.
      default: 4
  - sh_basis:
      type: string
      description: |
        Spherical harmonics basis to use. Options :
          - descoteaux07
          - tournier07
          - descoteaux07_legacy
          - tournier07_legacy
      default: "descoteaux07_legacy"
  - smoothing:
      type: float
      description: Regularization coefficient used for the spherical harmonics fit.
      default: 0.006
  - attenuation_only:
      type: boolean
      description: If enabled, divide the weighted volumes by the b0 before fitting.
      default: false
output:
  sh_signal:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*__dwi_sh.nii.gz":
          type: file
          description: Output filename for the SH coefficients.
          pattern: "*__dwi_sh.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@AlexVCaron"
maintainers:
  - "@AlexVCaron"
