# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: registration_anattodwi
description: Anatomical image registration on a diffusion image.
keywords:
  - nifti
  - registration
  - anatomical
  - dwi

tools:
  - ANTs:
      description: Advanced Normalization Tools (ANTs) for image processing.
      homepage: http://stnava.github.io/ANTs/
      doi: "10.1038/s41598-021-87564-6"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`

    - t1:
        type: file
        description: Nifti image file to register on dwi
        pattern: "*.{nii,nii.gz}"

    - b0:
        type: file
        description: Nifti image file - b0
        pattern: "*.{nii,nii.gz}"

    - metric:
        type: file
        description: Nifti image file metric used to register (fa)
        pattern: "*.{nii,nii.gz}"

output:
  - affine:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*0GenericAffine.mat":
          type: file
          description: Affine transformation matrix.
          pattern: "*0GenericAffine.mat"
  - warp:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*1Warp.nii.gz":
          type: file
          description: Warp field.
          pattern: "*1Warp.{nii,nii.gz}"
  - inverse_warp:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*1InverseWarp.nii.gz":
          type: file
          description: Inverse warp field.
          pattern: "*1InverseWarp.{nii,nii.gz}"
  - t1_warped:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*t1_warped.nii.gz":
          type: file
          description: Anatomical T1 warped to dwi space.
          pattern: "*t1_warped.{nii,nii.gz}"
  - mqc:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_registration_anattodwi_mqc.gif":
          type: file
          description: |
            .gif file containing quality control image for the
            registration process. For use in MultiQC report.
          pattern: "*_registration_anattodwi_mqc.gif"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - "@medde"
