# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: bundle_labelmap
description: |
  Compute the label image (Nifti) from a centroid and tractograms (all representing the same bundle).
  The label image represents the coverage of the bundle, segmented into regions labelled from 0 to
  --nb_pts, starting from the head, ending in the tail. Each voxel will have the label of its nearest
  centroid point. The number of labels will be the same as the centroid's number of points.
keywords:
  - bundle
  - distance
  - label
  - centroid
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - bundles:
        type: file
        description: List of trk files of the bundles
        pattern: "*.{trk}"
        mandatory: true
        ontologies: []
    - centroids:
        type: file
        description: List of trk files of the centroids
        pattern: "*.{trk}"
        mandatory: true
        ontologies: []
args:
  - nb_points:
      type: int
      description: Number of divisions for the bundles.
      default: Number of points of the centroid
  - colormap:
      type: string
      description: Select the colormap for colored trk (data_per_point).
      default: "jet"
  - new_labelling:
      type: boolean
      description: Use the new labelling method (multi-centroids).
      default: false
output:
  labels:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_labels.nii.gz":
          type: file
          description: Labels map, each pixel intensity corresponds to the label of
            the nearest centroid.
          pattern: "*_labels.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  labels_trk:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_labels.trk":
          type: file
          description: Colored by labels bundle file. The streamline color corresponds
            to the label of the nearest centroid.
          pattern: "*_labels.trk"
          ontologies: []
  distances:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_distances.nii.gz":
          type: file
          description: Distance map. The pixel intensity corresponds to the distance
            to the nearest centroid.
          pattern: "*_distances.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  distances_trk:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_distances.trk":
          type: file
          description: Colored by distance bundle file. The streamline color corresponds
            to the distance to the nearest centroid.
          pattern: "*_distances.trk"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@gagnonanthony"
