---
name: "stats_imageinroi"
description: Module to Compute the statistics (mean, std) of scalar maps, which can represent diffusion metrics, in ROIs or labels.
keywords:
  - nifti
  - volume
  - scilpy
  - stats
  - rois
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - images:
      type: files
      description: Metrics
      pattern: "*.{nii,nii.gz}"

  - rois:
      type: files
      description: ROI volume in Nifti
      pattern: "*.{nii,nii.gz}"

  - rois_lut:
      type: file
      description: LUT file corresponding to labels,used to name the regions of interest
      pattern: "*.{nii,nii.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - mqc:
      type: file
      description: JSON file containing mean/std per pair of roi/metrics or label/metrics
      pattern: "*__stats.json"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@arnaudbore"
