---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: registration_ants
description: Image registration with antsRegistrationSyN or antsRegistrationSyNQuick
keywords:
  - nifti
  - registration
  - antsRegistrationSyN
  - antsRegistrationSyNQuick
  - trk
tools:
  - ants:
      description: Advanced Normalization Tools.
      homepage: https://github.com/ANTsX/ANTs

      identifier: ""
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`

    - fixedimage:
        type: file
        description: Fixed image(s) or source image(s) or reference image(s)
        pattern: "*.{nii,nii.gz}"

    - movingimage:
        type: file
        description: Moving image(s) or target image(s)
        pattern: "*.{nii,nii.gz}"

    - mask:
        type: file
        description: Mask(s) for the fixed image space
        pattern: "*.{nii,nii.gz}"

output:
  - image:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_warped.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*_warped.nii.gz"
  - warp:
      - meta: {}
      - "*__output0Warp.nii.gz": {}
  - affine:
      - meta: {}
      - "*__output1GenericAffine.mat": {}
  - inverse_warp:
      - meta: {}
      - "*__output1InverseWarp.nii.gz": {}
  - inverse_affine:
      - meta: {}
      - "*__output0InverseAffine.mat": {}
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - "@ThoumyreStanislas"
