# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: registration_ants
description: Image registration with antsRegistrationSyN or antsRegistrationSyNQuick
keywords:
  - nifti
  - registration
  - antsRegistrationSyN
  - antsRegistrationSyNQuick
  - trk
tools:
  - ants:
      description: Advanced Normalization Tools.
      homepage: https://github.com/ANTsX/ANTs

      identifier: ""
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`

    - fixedimage:
        type: file
        description: Fixed image(s) or source image(s) or reference image(s)
        pattern: "*.{nii,nii.gz}"

    - movingimage:
        type: file
        description: Moving image(s) or target image(s)
        pattern: "*.{nii,nii.gz}"

    - mask:
        type: file
        description: Mask(s) for the fixed image space
        pattern: "*.{nii,nii.gz}"

output:
  - image:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`

      - "*_warped.nii.gz":
          type: file
          description: Nifti volume after registration.
          pattern: "*_warped.nii.gz"

  - affine:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`

      - "*__output0GenericAffine.mat":
          type: file
          description: Affine transformation from moving to fixed
          pattern: "*__output0GenericAffine.mat"

  - inverse_affine:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`

      - "*__output1InverseAffine.mat":
          type: file
          description: Affine transformation from fixed to moving
          pattern: "*__output1InverseAffine.mat"

  - warp:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`

      - "*__output1Warp.nii.gz":
          type: file
          description: Nifti volume containing warp field from moving to fixed
          pattern: "*__output1Warp.nii.gz"

  - inverse_warp:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`

      - "*__output0InverseWarp.nii.gz":
          type: file
          description: Nifti volume containing warp field from fixed to moving
          pattern: "*__output0InverseWarp.nii.gz"

  - mqc:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`

      - "*_registration_ants_mqc.gif":
          type: file
          description: .gif file containing quality control image for the registration process. Made for use in MultiQC report.
          pattern: "*_registration_ants_mqc.gif"

  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml

authors:
  - "@ThoumyreStanislas"
