# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: image_applymask
description: Apply a binary mask to a 3D or 4D image.
keywords:
  - Image
  - Mask
  - BET
tools:
  - MRtrix3:
      description: Toolbox for image processing, analysis and visualisation of dMRI.
      homepage: https://mrtrix.readthedocs.io/en/latest/

      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - image:
        type: file
        description: 3D or 4D image to apply the mask to.
        pattern: "*.nii.gz"

    - mask:
        type: file
        description: Binary mask to apply to the image.
        pattern: "*.nii.gz"

output:
  - image:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*masked.nii.gz":
          type: file
          description: Masked 3D or 4D image.
          pattern: "*masked.nii.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - "@gagnonanthony"
maintainers:
  - "@gagnonanthony"
