# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: image_applymask
description: Apply a binary mask to a 3D or 4D image.
keywords:
  - Image
  - Mask
  - BET
tools:
  - MRtrix3:
      description: |
        MRtrix3 is a software package for various types of diffusion imaging
        data, including diffusion-weighted, diffusion-tensor, and q-ball imaging.
      homepage: https://www.mrtrix.org/
      doi: 10.1016/j.neuroimage.2019.116137
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - image:
        type: file
        description: 3D or 4D image to apply the mask to.
        pattern: "*.nii.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
    - mask:
        type: file
        description: Binary mask to apply to the image.
        pattern: "*.nii.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
output:
  image:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*masked.nii.gz":
          type: file
          description: Masked 3D or 4D image.
          pattern: "*masked.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@gagnonanthony"
maintainers:
  - "@gagnonanthony"
