# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: preproc_normalize
description: Normalize DWI using MRtrix3 (in WM)
keywords:
  - nifti
  - normalise
  - scilpy
  - MRtrix3
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
  - MRtrix3:
      description: Toolbox for image processing, analysis and visualisation of dMRI.
      homepage: https://mrtrix.readthedocs.io/en/latest/

      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti image file to normalize
        pattern: "*.{nii,nii.gz}"
    - bval:
        type: file
        description: Text file containing b-values
        pattern: "*.{.bval}"
    - bvec:
        type: file
        description: Text file containing b-vectors
        pattern: "*.{.bvec}"
    - mask:
        type: file
        description: Nifti image file used to mask the input image
        pattern: "*.{nii,nii.gz}"
output:
  - dwi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*dwi_normalized.nii.gz":
          type: file
          description: Normalized Nifti image file
          pattern: "*dwi_normalized.{nii,nii.gz}"
  - mask:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*fa_wm_mask.nii.gz":
          type: file
          description: Nifti image file mask
          pattern: "*fa_wm_mask.{nii,nii.gz}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - "@scilus"
