---
# yaml-language-server: $schema=https://raw.githubusercontent.com/scilus/nf-neuro/main/modules/meta-schema.json
name: "preproc_n4"
description: |
  Perform N4 bias field correction on either an anatomical image or a diffusion
  volume. For diffusion volumes, the module automatically determines the
  bspline parameter, number of stages, and iteration pyramid based on the image
  resolution and size.

  The formula used are as follows:
  For the BSpline parameter:
  `BSplineParam = 2 ** (NbStages - 1) * BSplineKnotPerVoxel * ShrinkFactor * ImageResolution`

  For the number of stages in the iteration pyramid:
  If SmallestDimension ≤ BSplineKnotPerVoxel * ShrinkFactor:
      NbStages = 1
  Else:
      NbStages = ceil( log2(SmallestDimension / (BSplineKnotPerVoxel * ShrinkFactor)) )

  For the iteration pyramid:
  Slope     = (MinIter - MaxIter) / (1 - Retain)
  Intercept = MaxIter - Slope * Retain

  For i in linspace(0, 1, NbStages):
      If i < Retain:
          Iteration = MaxIter
      Else:
          Iteration = round(Slope * i + Intercept)

  The default values for the shrink_factor and bspline_knot_per_voxel are set
  to 4 and 8, respectively, which are suitable for most diffusion volumes from
  a large age range of subjects and species.

keywords:
  - correction
  - N4
  - bias field
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - image:
      type: file
      description: Nifti image file to correct
      pattern: "*.{nii,nii.gz}"

  - ref:
      type: file
      description: Nifti image file for the reference
      pattern: "*.{nii,nii.gz}"

  - ref_mask:
      type: file
      description: Nifti image file mask for the reference
      pattern: "*.{nii,nii.gz}"

args:
  - prefix:
      type: string
      description: Prefix to add to the output file name (e.g. "n4_")
  - bspline_knot_per_voxel:
      type: number
      description: Number of B-spline knots per voxel
      default: 8
  - shrink_factor:
      type: number
      description: Shrink factor for the image resampling.
      default: 4
  - maxiter:
      type: number
      description: Maximum number of iterations for the N4 algorithm.
      default: 1000
  - miniter:
      type: number
      description: Minimum number of iterations for the N4 algorithm.
      default: 100
  - retain:
      type: number
      description: Percentage of iterations to retain for deeper iterations.
      default: 0.6

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - image:
      type: file
      description: N4 corrected image
      pattern: "*.{nii,nii.gz}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@arnaudbore"
