---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: reconst_dtimetrics
description: Script to compute all of the Diffusion Tensor Imaging (DTI) metrics
keywords:
  - nifti
  - DTI
  - tensor
  - scilpy
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git

      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`

    - dwi:
        type: file
        description: Nifti DWI volume used to extract DTI metrics.
        pattern: "*.{nii,nii.gz}"

    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"

    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"

    - b0mask:
        type: file
        description: Nifti b0 volume file used to mask the input image.
        pattern: "*.{nii,nii.gz}"

output:
  - ad:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__ad.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__ad.{nii,nii.gz}"
  - evecs:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__evecs.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evecs.{nii,nii.gz}"
  - evecs_v1:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__evecs_v1.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evecs_v1.{nii,nii.gz}"
  - evecs_v2:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__evecs_v2.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evecs_v2.{nii,nii.gz}"
  - evecs_v3:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__evecs_v3.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evecs_v3.{nii,nii.gz}"
  - evals:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__evals.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evals.{nii,nii.gz}"
      - s:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evals.{nii,nii.gz}"
  - evals_e1:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__evals_e1.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evals_e1.{nii,nii.gz}"
      - s_e1:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evals_e1.{nii,nii.gz}"
  - evals_e2:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__evals_e2.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evals_e2.{nii,nii.gz}"
      - s_e2:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evals_e2.{nii,nii.gz}"
  - evals_e3:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__evals_e3.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evals_e3.{nii,nii.gz}"
      - s_e3:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__evals_e3.{nii,nii.gz}"
  - fa:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__fa.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__fa.{nii,nii.gz}"
  - ga:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__ga.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__ga.{nii,nii.gz}"
  - rgb:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__rgb.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__rgb.{nii,nii.gz}"
  - md:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__md.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__md.{nii,nii.gz}"
  - mode:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__mode.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__mode.{nii,nii.gz}"
  - norm:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__norm.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__norm.{nii,nii.gz}"
  - rd:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__rd.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__rd.{nii,nii.gz}"
  - tensor:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__tensor.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__tensor.{nii,nii.gz}"
  - nonphysical:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__nonphysical.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__nonphysical.{nii,nii.gz}"
  - pulsation_std_dwi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pulsation_std_dwi.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__pulsation_std_dwi.{nii,nii.gz}"
  - pulsation_std_b0:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pulsation_std_b0.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__pulsation_std_b0.{nii,nii.gz}"
  - residual:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__residual.nii.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__residual.{nii,nii.gz}"
  - residual_iqr_residuals:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__residual_iqr_residuals.npy":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__residual_iqr_residuals.npy"
  - residual_mean_residuals:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__residual_mean_residuals.npy":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__residual_mean_residuals.npy"
  - residual_q1_residuals:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__residual_q1_residuals.npy":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__residual_q1_residuals.npy"
  - residual_q3_residuals:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__residual_q3_residuals.npy":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__residual_q3_residuals.npy"
  - residual_residuals_stats:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__residual_residuals_stats.png":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__residual_residuals_stats.png"
  - residual_std_residuals:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__residual_std_residuals.npy":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*__residual_std_residuals.npy"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - "@scilus"
