# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: image_convert
description: |
  Small utility module to perform data type conversion on images. The new
  datatype has to be specified using the task.ext.datatype parameter, otherwise,
  the module will fail.
keywords:
  - image
  - convert
  - datatype
tools:
  - MRtrix3:
      description: |
        MRtrix3 is a software package for various types of diffusion imaging
        data, including diffusion-weighted, diffusion-tensor, and q-ball imaging.
      homepage: https://www.mrtrix.org/
      identifier: 10.1016/j.neuroimage.2019.116137
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - image:
        type: file
        description: Image to convert.
        pattern: "*.nii.gz"

output:
  - image:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`

      - "*_converted.nii.gz":
          type: file
          description: Image converted into the specified datatype.
          pattern: "*_converted.nii.gz"

  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml

authors:
  - "@gagnonanthony"
maintainers:
  - "@gagnonanthony"
