name: "reconst_dwishell"
description: Extracts the DWI volumes that are on specific b-value shells in
  the same order as in the original file.
keywords:
  - dwi
  - extract
  - shell
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti DWI volume.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIfTI format
    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"
        ontologies:
          - edam: http://edamontology.org/format_2330 # Plain text format
    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"
        ontologies:
          - edam: http://edamontology.org/format_2330 # Plain text format
args:
  - out_indices:
      type: boolean
      default: false
      description: Whether to output the valid indices of the input dwi volume.
  - block_size:
      type: integer
      default: null
      description: Useful when the data is too large to be loaded in memory. A
        block size of X means that X DWI volumes are loaded at a time for
        processing.
  - tolerance:
      type: integer
      default: 20
      description: The tolerated gap between the b-values to extract and the
        actual b-values.
output:
  dwi_shells:
    - - meta:
        type: map |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
      - "*__dwi_sh_shells.nii.gz":
          type: file
          description: DWI volume with shells fitted.
          pattern: "*__dwi_sh_shells.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIfTI format
      - "*__bval_sh_shells":
          type: file
          description: B-values of the fitted shells in FSL format.
          pattern: "*__bval_sh_shells"
          ontologies:
            - edam: http://edamontology.org/format_2330 # Plain text format
      - "*__bvec_sh_shells":
          type: file
          description: B-vectors of the fitted shells in FSL format.
          pattern: "*__bvec_sh_shells"
          ontologies:
            - edam: http://edamontology.org/format_2330 # Plain text format
  out_indices:
    - - meta:
        type: map |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
      - "*__out_indices":
          type: file
          description: Text file containing indices of the fitted shells.
          pattern: "*__out_indices"
          ontologies:
            - edam: http://edamontology.org/format_2330 # Plain text format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@levje"
maintainers:
  - "@levje"
