---
name: "mqc_gif"
description: generates quality control (QC) screenshots for for two images by comparing one to the other.
  It extracts middle slices (sagittal, coronal, and axial views) from both volumes,creates
  annotated mosaics, and combines them into an animated GIF for quick visual comparison.
keywords:
  - mqc
  - Visualisation
  - gif
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"
  - "MRtrix3":
      description: "MRtrix3 is a software package for various types of diffusion imaging data, including diffusion-weighted, diffusion-tensor, and q-ball imaging."
      homepage: "https://www.mrtrix.org/"
  - "imagemagick":
      description: "ImageMagick is a free, open-source software suite, used for editing and manipulating digital images."
      homepage: "https://imagemagick.org/index.php"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - image1:
      type: file
      description: first image to be analysed, typically for alignment with the seconde image.
      pattern: "*.{nii,nii.gz}"

  - image2:
      type: file
      description: seconde image to be analysed.
      pattern: "*.{nii,nii.gz}"

args:
  - title_image1:
      type: string
      description: name given to the first image

  - title_image2:
      type: string
      description: name given to the second image

  - suffix_qc:
      type: string
      description: suffix given to final image

  - fourth_dim:
      type: boolean
      default: false
      description: set to true if your input volumes contain a fourth dimension

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - mqc_screenshots:
      type: file
      description: .gif file containing quality control image for visually compares the warped and reference MRI volumes using middle-slice mosaics.
      pattern: "*_screenshots_merged_mqc.gif"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@ThoumyreStanislas"
