# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: segmentation_fsreconall
description: "Performs Freesurfer's recon-all script to segment your anatomy (probably
  a T1) into labels, surfaces, and much more. See the full documentation here: https://surfer.nmr.mgh.harvard.edu/fswiki/recon-all."
keywords:
  - neural network
  - Artificial intelligence
  - machine learning
  - Segmentation
  - Tissues
tools:
  - Freesurfer:
      description: |
        Open source neuroimaging toolkit for processing, analyzing, and visualizing human brain MR images.
      homepage: https://surfer.nmr.mgh.harvard.edu/
      doi: 10.1016/j.neuroimage.2012.01.021
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - anat:
        type: file
        description: An anatomy (ex, .nii.gz).
        pattern: "*.{nii,nii.gz,mgz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - fs_license:
        type: file
        description:
          The path to your FreeSurfer license. To get one, go to https://surfer.nmr.mgh.harvard.edu/registration.html.
          Optional. If you have already set your license as prescribed by Freesurfer
          (copied to a .license file in your $FREESURFER_HOME), this is not required.
        pattern: "*.txt"
        ontologies: []
output:
  recon_all_out_folder:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__recon_all":
          type: directory
          description: Directory containing all recon-all outputs.
          pattern: "*__recon_all"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@EmmaRenauld"
