name: Merge to main
on:
  workflow_dispatch:
  workflow_call:

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

jobs:
  publish-documentation:
    if: github.repository == 'scilus/nf-neuro'
    uses: scilus/nf-neuro-documentation/.github/workflows/deploy.yml@main
    secrets: inherit

  publish-extension-package:
    if: github.repository == 'scilus/nf-neuro'
    uses: ./.github/workflows/publish_extension.yml
    with:
      name: "extension-package"
    secrets: inherit
