name: "image_burnvoxels"
description: Burn voxels from masks into an anatomical image.
keywords:
  - Image Processing
  - Voxel Burning
  - Mask Application
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"
  - "ANTs":
      description: "Advanced Normalization Tools (ANTs) for image processing."
      homepage: "http://stnava.github.io/ANTs/"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - masks:
      type: list
      description: List of binary masks to be burned onto the anatomical image.
      pattern: "*.nii.gz"

  - anat:
      type: file
      description: Anatomical image to burn the masks onto.
      pattern: "*.nii.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - all_masks_burned:
      type: file
      description: Anatomical image with all masks burned onto it.
      pattern: "*.nii.gz"

  - each_mask_burned:
      type: list
      description: Anatomical image with each mask burned onto it.
      pattern: "*.nii.gz"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@GuillaumeTh"
maintainers:
  - "@GuillaumeTh"
